# Generated by Django 5.1 on 2024-08-29 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="drop_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="drop_location",
        ),
        migrations.RemoveField(
            model_name="car",
            name="drop_location",
        ),
        migrations.AddField(
            model_name="insurance",
            name="car",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="cars.car"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="type",
            field=models.CharField(
                choices=[
                    ("suv", "SUV"),
                    ("sedan", "Sedan"),
                    ("hatchback", "Hatchback"),
                    ("convertible", "Convertible"),
                    ("coupe", "Coupe"),
                    ("wagon", "Wagon"),
                    ("pickup", "Pickup Truck"),
                    ("minivan", "Minivan"),
                    ("sports", "Sports Car"),
                    ("luxury", "Luxury"),
                    ("cross_over", "Crossover"),
                    ("roadster", "Roadster"),
                    ("coupe_suv", "Coupe SUV"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(),
        ),
    ]
