# Generated by Django 5.1 on 2024-08-30 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0003_booking_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="pickup_location",
        ),
    ]
