# Generated by Django 5.1 on 2024-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0004_remove_booking_pickup_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_Available",
            field=models.BooleanField(default=True),
        ),
    ]
