# Generated by Django 5.1 on 2024-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_car_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="kms_driver",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
