# Generated by Django 5.1 on 2024-09-02 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0008_auto_20240902_2054"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="kms_driven",
            new_name="kms_driver",
        ),
    ]
