# Generated by Django 5.1 on 2024-09-02 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0009_rename_kms_driven_car_kms_driver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="kms_driver",
            new_name="kms_driven",
        )
    ]
