# Generated by Django 5.1 on 2024-09-02 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0011_remove_car_kms_driven_car_kms_driver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="kms_driver",
        ),
    ]
