# Generated by Django 5.1 on 2024-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0012_remove_car_kms_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="kms_driven",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
