# Generated by Django 5.1 on 2024-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0014_car_description_car_mileage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
