# Generated by Django 5.1.1 on 2024-09-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0015_alter_car_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="pincode",
            field=models.CharField(default="000000", max_length=10),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                    ("Electric", "Electric"),
                    ("Hybrid", "Hybrid"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="type",
            field=models.CharField(
                choices=[
                    ("Suv", "SUV"),
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                    ("Convertible", "Convertible"),
                    ("Coupe", "Coupe"),
                    ("Wagon", "Wagon"),
                    ("Pickup", "Pickup Truck"),
                    ("Minivan", "Minivan"),
                    ("Sports", "Sports Car"),
                    ("Luxury", "Luxury"),
                    ("Cross_over", "Crossover"),
                    ("Roadster", "Roadster"),
                    ("Coupe_suv", "Coupe SUV"),
                ],
                max_length=50,
            ),
        ),
    ]
