# Generated by Django 5.1 on 2024-08-29 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
